### ISSUE TITLE
7 train countdown times

### ISSUE THREAD

**Issue by tristanchase** [blahblahblah-/theweekendest#13]
Today I noticed that the countdown times for the 7 train weren't working normally. They were showing things like 1 min, 1min or DueDueDue, 1 min. Screenshot at 19:41 today 2021-03-11:

![Screenshot_20210311-194113](https://user-images.githubusercontent.com/12192992/110875358-78a08d00-82a3-11eb-89ba-2f05561f54b7.png)

**Comment by blahblahblah-** [comment]
Sorry for the late response, I totally did not see this until now. Can you tell me what browser you were using? And if this problem also occurs when viewing other stations?

**Comment by tristanchase** [comment]
This issue was fixed within a day or two of my original comment (2021). Not sure what the underlying issue was, but I have not seen this behavior since.
