### ISSUE TITLE
Startup gives only black screen

### ISSUE THREAD

**Issue by tristanchase** [blahblahblah-/theweekendest#16]
When I open this on my phone (Moto G6, Android 9), I briefly see the startup screen. It then goes completely black after a few seconds.

I have been using this site for 1-2 years and have not encountered this before.

**Comment by blahblahblah-** [comment]
There was a major code change that was released yesterday, so any cached version of the code would result in an error. I pushed a change that should force a refresh just now, can you try again?

**Comment by tristanchase** [comment]
I cleared the  browser cache (Chrome) and it seems to be fine now.
