### ISSUE TITLE
Map freezes or blacks out

### ISSUE THREAD

**Issue by tristanchase** [blahblahblah-/theweekendest#40]
After selecting a train in the drop-down box, the map freezes or goes black. This also happens after selecting a train bullet on the map.

These actions would normally zoom the map out to show the entire line.

I noticed the version of Mapbox was updated in the last commit. I have tried clearing the cache and restarting my browser with no luck.

**Comment by blahblahblah-** [comment]
Thanks for noticing and reporting this. I just confirmed that there was a breaking change in the upgraded version of Mapbox that caused this issue to only happen on mobile screens (I didn't notice earlier, because I only tested on desktop). I reverted the change and have deployed it.

**Comment by tristanchase** [comment]
Thank you for your rapid response!

Mobile version is working again.
